behaviors:
    Fight:
        trainer_type: ppo
        keep_checkpoints: 10
        max_steps: 1e8
        time_horizon: 1000
        summary_freq: 10000
        threaded: true

        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 1
            vis_encode_type: simple

        hyperparameters:
            batch_size: 1024
            buffer_size: 86016 # 6 executables x 14 agents x 1024
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear

        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
